### PR TITLE
Minor tweaks to style.css to fix Career page text and SM icons

### PR DESCRIPTION
**Pull request by BelcherCharles**
Fixed font conflicts so <p>, <a>, and <li> should be in Arial. Also fixed SM links in footer to have icons instead of text.

### CODE REVIEW

**Comment by nikx1015** [comment]
👍

**Comment by MattRowee** [comment]
🎋

**Comment by Downeastrussell** [comment]
🔫

**Comment by CreativeFitz** [comment]
👍

**Pull request merged**
